#!/usr/bin/env bash

set -e  # Exit on error
set -o pipefail

# Source environment variables if .env exists in PWD
if [ -f "$PWD/.env" ]; then
  source "$PWD/.env"
fi

# Configuration
API_URL="${CLERK_REST_API_URL:-https://api.clerk.com}"
API_KEY="${CLERK_PLATFORM_TOKEN}"

# Check for required environment variable
if [ -z "$API_KEY" ]; then
  echo "Error: Missing CLERK_PLATFORM_TOKEN environment variable" >&2
  exit 1
fi

# Check for required dependencies
if ! command -v node &> /dev/null; then
  echo "Error: Node.js is required but not installed. Install from: https://nodejs.org" >&2
  exit 1
fi

# Default values
TEMPLATE="b2b-saas"
OUTPUT_DIR_ARG=""

# Parse command-line options
while getopts "t:o:" opt; do
  case $opt in
    t) TEMPLATE="$OPTARG" ;;
    o) OUTPUT_DIR_ARG="$OPTARG" ;;
    \?)
      echo "Usage: $0 <name> [-t template] [-o output]" >&2
      echo "  <name>        Project name (required)" >&2
      echo "  -t template   Template: b2b-saas (default), b2c-saas, or waitlist" >&2
      echo "  -o output     Output directory (optional)" >&2
      exit 1
      ;;
  esac
done

# Shift past the parsed options
shift $((OPTIND - 1))

# Get project name from first remaining positional argument
PROJECT_NAME="${1:-}"

if [ -z "$PROJECT_NAME" ]; then
  echo "Error: Project name is required" >&2
  echo "Usage: $0 <name> [-t template] [-o output]" >&2
  exit 1
fi

# Validate template
case "$TEMPLATE" in
  b2b-saas|b2c-saas|waitlist) ;;
  *)
    echo "Error: Invalid template '$TEMPLATE'. Must be one of: b2b-saas, b2c-saas, waitlist" >&2
    exit 1
    ;;
esac

# Determine output directory
if [ -n "$OUTPUT_DIR_ARG" ]; then
  OUTPUT_DIR="$(pwd)/$OUTPUT_DIR_ARG"
else
  OUTPUT_DIR="$(pwd)"
fi

# Create Clerk application via API
echo "Creating Clerk application: $PROJECT_NAME"

RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "$API_URL/v1/platform/applications" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $API_KEY" \
  -d "{
    \"name\": \"$PROJECT_NAME\",
    \"environment_types\": [\"development\"],
    \"template\": \"$TEMPLATE\"
  }")

# Split response body and HTTP status code
HTTP_BODY=$(echo "$RESPONSE" | head -n -1)
HTTP_CODE=$(echo "$RESPONSE" | tail -n 1)

# Check for API errors
if [ "$HTTP_CODE" -lt 200 ] || [ "$HTTP_CODE" -ge 300 ]; then
  echo "Error: API request failed with status $HTTP_CODE" >&2
  echo "$HTTP_BODY" >&2
  exit 1
fi

# Parse JSON response using Node.js
APP_ID=$(echo "$HTTP_BODY" | node -e "const data = JSON.parse(require('fs').readFileSync(0, 'utf-8')); console.log(data.application_id);")
PUBLISHABLE_KEY=$(echo "$HTTP_BODY" | node -e "const data = JSON.parse(require('fs').readFileSync(0, 'utf-8')); console.log(data.instances[0].publishable_key);")
SECRET_KEY=$(echo "$HTTP_BODY" | node -e "const data = JSON.parse(require('fs').readFileSync(0, 'utf-8')); console.log(data.instances[0].secret_key);")

# Validate parsed data
if [ "$APP_ID" = "null" ] || [ "$PUBLISHABLE_KEY" = "null" ] || [ "$SECRET_KEY" = "null" ]; then
  echo "Error: Failed to parse API response" >&2
  echo "Response: $HTTP_BODY" >&2
  exit 1
fi

# Create project directory
if [ ! -d "$OUTPUT_DIR" ]; then
  mkdir -p "$OUTPUT_DIR"
  echo "Created project directory: $OUTPUT_DIR"
else
  echo "Project directory already exists: $OUTPUT_DIR"
fi

# Create or append to .env.local file
if [ ! -f "$OUTPUT_DIR/.env.local" ]; then
  echo "Creating env file: $OUTPUT_DIR/.env.local"
  cat > "$OUTPUT_DIR/.env.local" << EOF
# Generated by clerk-skills
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$PUBLISHABLE_KEY
CLERK_SECRET_KEY=$SECRET_KEY
CLERK_APP_ID=$APP_ID
EOF
else
  echo "Appending to existing env file: $OUTPUT_DIR/.env.local"
  cat >> "$OUTPUT_DIR/.env.local" << EOF

# Generated by clerk-skills
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$PUBLISHABLE_KEY
CLERK_SECRET_KEY=$SECRET_KEY
CLERK_APP_ID=$APP_ID
EOF
fi

echo ""
echo "✓ Project created successfully!"
echo "  Directory: $OUTPUT_DIR"
echo "  App ID: $APP_ID"
