#!/usr/bin/env bash

set -e  # Exit on error
set -o pipefail

# Check for clerk CLI
if ! command -v clerk &> /dev/null; then
  echo "Error: Clerk CLI is required but not installed." >&2
  exit 1
fi

# Default values
TEMPLATE=""
OUTPUT_DIR_ARG=""
PROJECT_NAME=""

# Parse command-line options
while [ $# -gt 0 ]; do
  case "$1" in
    -t) TEMPLATE="$2"; shift 2 ;;
    -o) OUTPUT_DIR_ARG="$2"; shift 2 ;;
    -h|--help)
      echo "Usage: $0 <name> [-t template] [-o output]" >&2
      echo "  <name>        Project name (required)" >&2
      echo "  -t template   Template: b2b-saas, b2c-saas, or waitlist" >&2
      echo "  -o output     Output directory (optional)" >&2
      exit 0
      ;;
    -*) echo "Unknown option: $1" >&2; exit 1 ;;
    *) PROJECT_NAME="$1"; shift ;;
  esac
done

if [ -z "$PROJECT_NAME" ]; then
  echo "Error: Project name is required" >&2
  echo "Usage: $0 <name> [-t template] [-o output]" >&2
  exit 1
fi

# Determine output directory
if [ -n "$OUTPUT_DIR_ARG" ]; then
  OUTPUT_DIR="$(pwd)/$OUTPUT_DIR_ARG"
else
  OUTPUT_DIR="$(pwd)"
fi

# Build clerk CLI command
CMD="clerk apps create --name \"$PROJECT_NAME\" --output json"
if [ -n "$TEMPLATE" ]; then
  CMD="$CMD --template $TEMPLATE"
fi

echo "Creating Clerk application: $PROJECT_NAME"

# Run clerk CLI and capture JSON output
RESPONSE=$(eval "$CMD")

# Parse JSON response using node
APP_ID=$(echo "$RESPONSE" | node -e "const d=JSON.parse(require('fs').readFileSync(0,'utf-8')); console.log(d.application_id);")
PUBLISHABLE_KEY=$(echo "$RESPONSE" | node -e "const d=JSON.parse(require('fs').readFileSync(0,'utf-8')); console.log(d.instances[0].publishable_key);")
SECRET_KEY=$(echo "$RESPONSE" | node -e "const d=JSON.parse(require('fs').readFileSync(0,'utf-8')); console.log(d.instances[0].secret_key);")

# Validate parsed data
if [ "$APP_ID" = "null" ] || [ "$PUBLISHABLE_KEY" = "null" ] || [ "$SECRET_KEY" = "null" ]; then
  echo "Error: Failed to parse CLI response" >&2
  echo "Response: $RESPONSE" >&2
  exit 1
fi

# Create project directory
if [ ! -d "$OUTPUT_DIR" ]; then
  mkdir -p "$OUTPUT_DIR"
  echo "Created project directory: $OUTPUT_DIR"
fi

# Create or append to .env.local file
if [ ! -f "$OUTPUT_DIR/.env.local" ]; then
  echo "Creating env file: $OUTPUT_DIR/.env.local"
  cat > "$OUTPUT_DIR/.env.local" << EOF
# Generated by clerk-skills
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$PUBLISHABLE_KEY
CLERK_SECRET_KEY=$SECRET_KEY
CLERK_APP_ID=$APP_ID
EOF
else
  echo "Appending to existing env file: $OUTPUT_DIR/.env.local"
  cat >> "$OUTPUT_DIR/.env.local" << EOF

# Generated by clerk-skills
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$PUBLISHABLE_KEY
CLERK_SECRET_KEY=$SECRET_KEY
CLERK_APP_ID=$APP_ID
EOF
fi

echo ""
echo "Done! App created successfully."
echo "  Directory: $OUTPUT_DIR"
echo "  App ID: $APP_ID"
