name: Check plugin manifests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-plugin:
    name: Check plugin manifests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: python3 scripts/check.py
